# Generated by Django 6.0.5 on 2026-05-22 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('genre', models.CharField(choices=[('artistic', 'ARTISTIC'), ('comedy', 'COMEDY'), ('historical', 'HISTORICAL'), ('adventure', 'ADVENTURE'), ('fantastic', 'FANTASTIC')], max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('photo', models.ImageField(default='books/default_img.avif', upload_to='books/')),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
                'db_table': 'books',
            },
        ),
    ]
